In [37]:
import pandas as pd

# Lire le fichier Excel
file = pd.ExcelFile("annotation_autres.xlsx")

# Liste des colonnes communes
colonnes_communes = ["Question", "Doc ID", "RRF Score", "Content", "Annotation"]

# Initialiser une liste pour stocker les DataFrames de chaque feuille
dataframes = []

# Parcourir chaque feuille du fichier Excel
for sheet_name in file.sheet_names:
    # Lire la feuille actuelle
    df = pd.read_excel(file, sheet_name=sheet_name)

    # Sélectionner uniquement les colonnes communes
    df_commun = df[colonnes_communes]

    # Ajouter le DataFrame filtré à la liste
    dataframes.append(df_commun)

# Concaténer tous les DataFrames de la liste
resultat_autres = pd.concat(dataframes, ignore_index=True)

# Afficher le résultat
print(resultat_autres["Annotation"].notna().sum())
resultat_autres[resultat_autres["Annotation"].notna()].sort_values(by=["Question","Annotation"])

608

,Question,Doc ID,RRF Score,Content,Annotation
131,Alimentation chaudières auxiliaire FOD FA3 dém...,{'original_doc_id': 'baseeqt_20200506.xlsx.txt...,1.935527,N S QS NC NC NC ART7 NS ROB FA3 3 CET 1201 TY-...,0.0
133,Alimentation chaudières auxiliaire FOD FA3 dém...,{'original_doc_id': 'produits utilisés.xls.txt...,0.051155,07.2018\t-2\t\tPCE\t\t\t\t\t\t\t\tAP3FB4AN\tAL...,0.0
134,Alimentation chaudières auxiliaire FOD FA3 dém...,"{'original_doc_id': 'cdv.xlsx.txt', 'source_in...",0.037037,Sheet: Feuil1 Activités Matières premières Uti...,0.0
135,Alimentation chaudières auxiliaire FOD FA3 dém...,{'original_doc_id': 'impression_etiquettes_con...,0.023256,à fioul Extérieur Extérieur Extérieur 4734-2.c...,0.0
136,Alimentation chaudières auxiliaire FOD FA3 dém...,{'original_doc_id': 'export-1000000083-install...,0.016667,l'unitÃ© de dessalement d'eau de mer destinÃ©e...,0.0
...,...,...,...,...,...
526,Études sureté RDS marges critères,"{'original_doc_id': 'qiz1eJcB37Fmqa9nrELp', 's...",0.037037,engendrerait des rejets vapeurs du même ordre ...,2.0
528,Études sureté RDS marges critères,"{'original_doc_id': 'KSz1eJcB37Fmqa9nRCTn', 's...",0.023256,5922006810. Cette note conclut à un impact min...,2.0
531,Études sureté RDS marges critères,"{'original_doc_id': 'iiz1eJcB37Fmqa9nTyob', 's...",0.014085,nés parmi les données d’entrée du calcul. L’éc...,2.0
532,Études sureté RDS marges critères,"{'original_doc_id': 'dyz1eJcB37Fmqa9nrEPp', 's...",0.018868,effets axiaux des modèles BR. Impact non prése...,2.0
1373,Études sureté RDS marges critères,{'original_doc_id': 'guide rédaction facr epr ...,0.213584,ou autorisées à y accéder. Il est illégal de p...,2.0

In [ ]:
resultat_autres.sort_values('Question')

In [33]:
import pandas as pd

# Lire le fichier Excel
file = pd.ExcelFile("2eme_annotation_manuelle.xlsx")

# Liste des colonnes communes
colonnes_communes = ["Question", "Doc ID", "RRF Score", "Content", "Annotation"]

# Initialiser une liste pour stocker les DataFrames de chaque feuille
dataframes = []

# Parcourir chaque feuille du fichier Excel
for sheet_name in file.sheet_names:
    # Lire la feuille actuelle
    df = pd.read_excel(file, sheet_name=sheet_name)

    # Sélectionner uniquement les colonnes communes
    df_commun = df[colonnes_communes]

    # Ajouter le DataFrame filtré à la liste
    dataframes.append(df_commun)

# Concaténer tous les DataFrames de la liste
duexieme_annotation_manuelle = pd.concat(dataframes, ignore_index=True)

# Afficher le résultat
print(duexieme_annotation_manuelle["Annotation"].notna().sum())
duexieme_annotation_manuelle

165

,Question,Doc ID,RRF Score,Content,Annotation
0,Installations EPR Classées protection environn...,{'original_doc_id': 'copie de exigence à vérif...,0.793464,de stockage de déchet pour éviter tout risque ...,NaN
1,Installations EPR Classées protection environn...,{'original_doc_id': 'gestion documentaire au 2...,0.167832,installation et maintenance de matériel de pro...,NaN
2,Installations EPR Classées protection environn...,{'original_doc_id': 'indicateurs enviro par so...,0.125000,existed on 8 february 2012 0 3 145 4 624 0 0 E...,NaN
3,Installations EPR Classées protection environn...,{'original_doc_id': 'copie de indicateur afa a...,0.076923,onnement / Environment Installation nucléaire ...,NaN
4,Installations EPR Classées protection environn...,{'original_doc_id': 'areva ffp_d02-arv-01-064-...,0.047619,IP Activité Importante pour la Protection (des...,NaN
...,...,...,...,...,...
2795,Conformité réglementaire plan management envir...,{'original_doc_id': 'présentation secu env.ppt...,0.050000,Plan de Management Sécurité Environnement Radi...,NaN
2796,Conformité réglementaire plan management envir...,{'original_doc_id': 'ins epr 613 ind e versio...,0.043478,ité dans l’outil HSE Compliance. La vérificati...,NaN
2797,Conformité réglementaire plan management envir...,"{'original_doc_id': ""proposition plan d'action...",0.037037,directives groupe. en attente des directives g...,NaN
2798,Conformité réglementaire plan management envir...,{'original_doc_id': '02 - bilan environnement ...,0.029412,tiée) Obtention des agréments des déchets Evac...,NaN
2799,Conformité réglementaire plan management envir...,{'original_doc_id': 'doc by-dtp au 080914.xlsx...,0.029412,de l'environnement de SEMA E PREL 2012-03-23 2...,NaN

In [34]:
import pandas as pd

# Lire le fichier Excel
file = pd.ExcelFile("génie_civile.xlsx")

# Liste des colonnes communes
colonnes_communes = ["Question", "Doc ID", "RRF Score", "Content", "Annotation"]

# Initialiser une liste pour stocker les DataFrames de chaque feuille
dataframes = []

# Parcourir chaque feuille du fichier Excel
for sheet_name in file.sheet_names:
    # Lire la feuille actuelle
    df = pd.read_excel(file, sheet_name=sheet_name)

    # Sélectionner uniquement les colonnes communes
    df_commun = df[colonnes_communes]

    # Ajouter le DataFrame filtré à la liste
    dataframes.append(df_commun)

# Concaténer tous les DataFrames de la liste
genie_civile = pd.concat(dataframes, ignore_index=True)

# Afficher le résultat
print(genie_civile["Annotation"].notna().sum())
genie_civile

327

,Question,Doc ID,RRF Score,Content,Annotation
0,Bonne étude dimensionnement bâtiment Génie Civil,{'original_doc_id': 'copie de export_demandes_...,0.430805,s vitales 2019-08-06 Bonne Pratique Lot Génie ...,0.0
1,Bonne étude dimensionnement bâtiment Génie Civil,{'original_doc_id': 'matrice ae_11-2022.xlsx.t...,0.166667,collecte des effluents de vidange des réseaux ...,0.0
2,Bonne étude dimensionnement bâtiment Génie Civil,"{'original_doc_id': 'matrice ae.xlsx.txt', 'so...",0.141667,dans le réseau grâce aux obturateurs gonflable...,0.0
3,Bonne étude dimensionnement bâtiment Génie Civil,{'original_doc_id': 'copie de cg_revue activit...,0.111111,Sheet: GC ACTIVITE entré/sortie ASPECT Détails...,0.0
4,Bonne étude dimensionnement bâtiment Génie Civil,"{'original_doc_id': 'cg_1.xlsx.txt', 'source_i...",0.083333,Sheet: GC ACTIVITE ASPECT Détails et descripti...,0.0
...,...,...,...,...,...
2052,Coût construction béton bâtiment HR FA3,"{'original_doc_id': 'qSz1eJcB37Fmqa9naCwV', 's...",0.047619,C0000531645 DPC DSPP Montrouge - Park Azur Con...,NaN
2053,Coût construction béton bâtiment HR FA3,"{'original_doc_id': 'dSz1eJcB37Fmqa9nhT30', 's...",0.041667,née d'entrée pour la vérification de la tenue ...,NaN
2054,Coût construction béton bâtiment HR FA3,"{'original_doc_id': 'iCz1eJcB37Fmqa9nUSzk', 's...",0.037037,C0000531261 DPC DSPP Montrouge - Park Azur Con...,NaN
2055,Coût construction béton bâtiment HR FA3,"{'original_doc_id': 'iyz1eJcB37Fmqa9nSCUH', 's...",0.033333,C0000231269 DISC EDVANCE Fla 3 Constat spontan...,NaN
2056,Coût construction béton bâtiment HR FA3,"{'original_doc_id': 'kCz1eJcB37Fmqa9ndTR6', 's...",0.034483,ling pour éviter les claschs dans les zones co...,NaN

In [39]:
dataframes = [resultat_autres, duexieme_annotation_manuelle, genie_civile]

# Concaténer les DataFrames
annotation_automatique = pd.concat(dataframes, ignore_index=True)

annotation_automatique["Annotation"].value_counts()

Annotation
0.0    619
1.0    249
2.0    232
Name: count, dtype: int64

In [42]:
annotation_automatique[annotation_automatique["Annotation"].notna()].sort_values(
    by=["Question", "Annotation"]
).to_excel("all_resultats_annotation.xlsx")

In [29]:
import pandas as pd

# Lire le fichier Excel
file = pd.ExcelFile("Annotation manuelle.xlsx")

# Liste des colonnes communes
colonnes_communes = ["Question", "Passage Pertinent"]

# Initialiser une liste pour stocker les DataFrames de chaque feuille
dataframes = []

# Parcourir chaque feuille du fichier Excel
for sheet_name in file.sheet_names:
    # Lire la feuille actuelle
    df = pd.read_excel(file, sheet_name=sheet_name)
    
    # Sélectionner uniquement les colonnes communes
    df_commun = df[colonnes_communes]

    # Ajouter le DataFrame filtré à la liste
    dataframes.append(df_commun)

# Concaténer tous les DataFrames de la liste
annotation_manuelle = pd.concat(dataframes, ignore_index=True)

# Afficher le résultat
annotation_manuelle

,Question,Passage Pertinent
0,Quel REX ou aléa trouves-tu sur les détecteurs...,Le fonctionnement sous eau de la configuration...
1,As-tu du REX sur l’installation des guides de ...,A la sortie des ERE023 et au début de la séque...
2,"As-tu du REX sur les aléas du peson 1,5 tonne ...",Après une manutention en mode normal (<23 tonn...
3,En préparation de la séquence chargement combu...,"En préparation de la séquence, il a été nécess..."
4,Quelles sont les Installations de l'EPR Classé...,Ce chapitre recense les Installations Classées...
...,...,...
156,Question 2 : Quelle société s'est chargée de c...,\tCOLLECTE\tCOLLECTE ANNUELLE\tCOUT LOCATION\t...
157,Question 3 : Combien y a t il d'ingénieur envi...,Réponse sous la forme d'un power point sans ex...
158,NaN,NaN
159,Quelles sont les étapes à réaliser en amont po...,Avant d’introduire les produits dangereux sur ...
160,Comment la conformité réglementaire est prise ...,Le Plan de Management Environnemental vise à é...